# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js check

on:
  push:
    branches: [ "beta" ]
  pull_request:
    branches: [ "beta" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install packages
      run: npm install
    - name: Run CI
      run: npm ci
    - name: Build the project
      run: |
        > .env.local
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env.local
        echo DB_URL=${{ secrets.DB_URL }} >> .env.local
        echo USERS_READ=${{ secrets.USERS_READ }} >> .env.local
        echo USERS_READ_PW=${{ secrets.USERS_READ_PW }} >> .env.local
        echo USERS_WRITE=${{ secrets.USERS_WRITE }} >> .env.local
        echo USERS_WRITE_PW=${{ secrets.USERS_WRITE_PW }} >> .env.local
        npm run build --if-present
