name: Playwright Tests
on:
  push:
    branches: [ main, beta ]
  pull_request:
    branches: [ main, beta ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: extract current branch
      run: |
        CURRENT_BRANCH=$(echo $GITHUB_REF | sed -e 's/refs\/heads\///g' | sed -e 's/_//g')
        URL=https://nextjs-password-safe-git-$CURRENT_BRANCH-four-man-army.vercel.app/
        echo $CURRENT_BRANCH
        echo $URL
    - name: create env file
      run: |
        touch .env
        echo PASSWORD=${{secrets.PASSWORD}} >> .env
        echo EMAIL=${{secrets.EMAIL}} >> .env
        echo TEST_URL=$URL >> .env
        echo CI=true >> .env
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run test
      env:
        PASSWORD: ${{secrets.PASSWORD}}
        EMAIL: ${{secrets.EMAIL}}
        TEST_URL: $URL
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
